INFO 2023-04-22 14:36:43,147 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 14:36:46,212 basehttp "GET /news/ HTTP/1.1" 200 23929
INFO 2023-04-22 14:37:51,833 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\news\views.py changed, reloading.
INFO 2023-04-22 14:37:53,002 autoreload Watching for file changes with StatReloader
ERROR 2023-04-22 14:37:56,108 log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\news\views.py", line 24, in index
    logger.error(sa)
NameError: name 'sa' is not defined
ERROR 2023-04-22 14:37:56,161 basehttp "GET /news/ HTTP/1.1" 500 74502
INFO 2023-04-22 14:38:19,037 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\news\views.py changed, reloading.
INFO 2023-04-22 14:38:20,219 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 14:38:27,391 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\news\views.py changed, reloading.
INFO 2023-04-22 14:38:28,604 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 14:38:31,303 basehttp "GET /news/ HTTP/1.1" 200 23929
INFO 2023-04-22 14:41:40,617 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\news\views.py changed, reloading.
INFO 2023-04-22 14:41:41,990 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 14:41:45,593 basehttp "GET /news/ HTTP/1.1" 200 23929
INFO 2023-04-22 14:52:33,416 basehttp "GET /news/categories/5 HTTP/1.1" 200 9017
INFO 2023-04-22 14:52:35,953 basehttp "GET /news/34 HTTP/1.1" 200 5243
INFO 2023-04-22 14:52:39,040 basehttp "GET /news/ HTTP/1.1" 200 23929
INFO 2023-04-22 15:02:03,110 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:09:23,496 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\NewsPaper\settings.py changed, reloading.
INFO 2023-04-22 15:09:25,092 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:13:02,216 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\NewsPaper\settings.py changed, reloading.
INFO 2023-04-22 15:13:03,512 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:14:51,096 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\NewsPaper\settings.py changed, reloading.
INFO 2023-04-22 15:14:52,289 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:16:07,190 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\NewsPaper\settings.py changed, reloading.
INFO 2023-04-22 15:16:08,419 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:18:17,666 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\NewsPaper\settings.py changed, reloading.
INFO 2023-04-22 15:18:18,849 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:19:51,813 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\NewsPaper\settings.py changed, reloading.
INFO 2023-04-22 15:19:53,150 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:22:39,604 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\NewsPaper\settings.py changed, reloading.
INFO 2023-04-22 15:22:40,772 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:23:56,457 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:24:50,795 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:25:17,933 autoreload Watching for file changes with StatReloader
ERROR 2023-04-22 15:25:21,365 log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\news\views.py", line 27, in index
    return render(request, 'posts.html', context={'posts': posts})
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Asus\PycharmProjects\Django\NewsPaper1\venv\lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 84: 'endblock'. Did you forget to register or load this tag?
ERROR 2023-04-22 15:25:21,461 basehttp "GET /news/ HTTP/1.1" 500 196771
INFO 2023-04-22 15:25:54,680 autoreload Watching for file changes with StatReloader
INFO 2023-04-22 15:32:42,628 autoreload C:\Users\Asus\PycharmProjects\Django\NewsPaper1\NewsPaper\NewsPaper\settings.py changed, reloading.
